public import Distributed

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif

/// A type with a JSON Schema: what every type in a discoverable actor's signature needs.
///
/// The library conforms the types it knows, such as `String`, `Date`, and arrays of
/// conforming types, and `@Discoverable` actors conform as references. Structures and
/// enumerations get a conformance from ``Describable()``; conform by hand for formats
/// or constraints the macro can't express.
public protocol Describable {
    static var jsonSchema: JSONValue { get }
}

/// JSON Schemas for Swift types, as discovery describes them.
///
/// ``schema(for:)`` is public API: use it to describe types you know, the same way
/// `describe()` does. Types join discovery by conforming to ``Describable``.
/// Everything else generated code needs lives in `_DiscoverySupport`.
public enum Discovery {
    /// One argument of an action.
    public struct Parameter: Sendable {
        public var name: String
        public var schema: JSONValue
        public var isOptional: Bool

        public init(name: String, schema: JSONValue, isOptional: Bool) {
            self.name = name
            self.schema = schema
            self.isOptional = isOptional
        }
    }

    static func schema(description: String?, parameters: [Parameter]) -> JSONValue? {
        guard !parameters.isEmpty else { return nil }
        var properties: [String: JSONValue] = [:]
        for parameter in parameters {
            properties[parameter.name] = parameter.schema
        }
        var object: [String: JSONValue] = [
            "type": "object",
            "properties": .object(properties),
            "required": .array(parameters.filter { !$0.isOptional }.map { .string($0.name) }),
            "additionalProperties": false,
        ]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of a structure's fields, for code generated by ``Describable()``.
    static func objectSchema(description: String?, fields: [Parameter]) -> JSONValue {
        var properties: [String: JSONValue] = [:]
        for field in fields {
            properties[field.name] = field.schema
        }
        var object: [String: JSONValue] = [
            "type": "object",
            "properties": .object(properties),
            "required": .array(fields.filter { !$0.isOptional }.map { .string($0.name) }),
        ]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of an enumeration's raw values, for code generated by ``Describable()``.
    ///
    /// Values with descriptions are listed as `oneOf` constants, so each keeps its description.
    static func enumSchema(description: String?, cases: [(value: JSONValue, description: String?)]) -> JSONValue {
        var object: [String: JSONValue] = [:]
        if let first = cases.first?.value {
            object["type"] =
                if case .string = first { "string" } else if case .number = first { "number" } else { "integer" }
        }
        if cases.contains(where: { $0.description != nil }) {
            object["oneOf"] = .array(cases.map { describing(["const": $0.value], $0.description) })
        } else {
            object["enum"] = .array(cases.map(\.value))
        }
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of an enumeration with associated values, in the shape synthesized `Codable`
    /// produces: an object with one key, the case name, holding the associated values.
    static func taggedSchema(
        description: String?,
        cases: [(name: String, description: String?, fields: [Parameter])]
    ) -> JSONValue {
        let options: [JSONValue] = cases.map { tagged in
            [
                "type": "object",
                "properties": [tagged.name: objectSchema(description: tagged.description, fields: tagged.fields)],
                "required": [.string(tagged.name)],
                "additionalProperties": false,
            ]
        }
        var object: [String: JSONValue] = ["oneOf": .array(options)]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    static func validate(_ arguments: JSONValue, allowedKeys: [String]) throws {
        guard case .object(let values) = arguments else {
            if arguments == .null { return }
            throw DiscoveryError.invalidArgument(
                name: "arguments", reason: "expected object, got \(arguments.kind)")
        }
        if let extra = values.keys.sorted().first(where: { !allowedKeys.contains($0) }) {
            throw DiscoveryError.unexpectedArgument(extra)
        }
    }

    public static func parameter<Value: Decodable>(
        _ name: String,
        description: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), description), isOptional: false)
    }

    public static func optionalParameter<Value: Decodable>(
        _ name: String,
        description: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), description), isOptional: true)
    }

    static func argument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value {
        guard let value = try optionalArgument(type, name, in: arguments, actorSystem: actorSystem) else {
            throw DiscoveryError.missingArgument(name)
        }
        return value
    }

    static func optionalArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value? {
        guard let value = arguments[name], value != .null else { return nil }
        return try decodeArgument(type, name, from: value, actorSystem: actorSystem)
    }

    static func defaultedArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil,
        default defaultValue: @autoclosure () -> Value
    ) throws -> Value {
        guard let value = arguments[name] else { return defaultValue() }
        return try decodeArgument(type, name, from: value, actorSystem: actorSystem)
    }

    /// Decodes an argument, turning a `DecodingError`, which actor systems can't send back to a
    /// remote caller, into ``DiscoveryError/invalidArgument(name:reason:)``.
    ///
    /// A distributed actor argument is passed as the reference `invoke` returns for it,
    /// `{"id": …}`, and resolved with the receiving actor's system.
    private static func decodeArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        from value: JSONValue,
        actorSystem: (any DistributedActorSystem)?
    ) throws -> Value {
        do {
            return try value.decode(type, actorSystem: actorSystem)
        } catch let error as DecodingError {
            throw DiscoveryError.invalidArgument(name: name, reason: reason(for: error, in: value))
        } catch {
            // A hand-written `init(from:)` may throw its own validation error.
            throw DiscoveryError.invalidArgument(name: name, reason: String(describing: error))
        }
    }

    /// A short explanation of a decoding failure in JSON terms, such as
    /// `expected integer, got string at authors[0].born`.
    static func reason(for error: DecodingError, in value: JSONValue) -> String {
        switch error {
        case .typeMismatch(let type, let context):
            let found = value.value(at: context.codingPath).map(\.kind) ?? "nothing"
            return "expected \(kind(of: type)), got \(found)\(location(context.codingPath))"
        case .valueNotFound(let type, let context):
            return "expected \(kind(of: type)), got null\(location(context.codingPath))"
        case .keyNotFound(let key, let context):
            return "missing \"\(key.stringValue)\"\(location(context.codingPath))"
        case .dataCorrupted(let context):
            return "\(context.debugDescription)\(location(context.codingPath))"
        @unknown default:
            return "\(error)"
        }
    }

    private static func location(_ path: [any CodingKey]) -> String {
        guard !path.isEmpty else { return "" }
        var text = ""
        for key in path {
            if let index = key.intValue {
                text += "[\(index)]"
            } else {
                text += text.isEmpty ? key.stringValue : ".\(key.stringValue)"
            }
        }
        return " at \(text)"
    }

    /// The JSON kind a type decodes from, taken from its schema, so that types such as
    /// `Decimal` or `UUID` are reported by their JSON form rather than their Swift name.
    private static func kind(of type: Any.Type) -> String {
        if case .string(let kind)? = schema(for: type)["type"] { return kind }
        return "\(type)"
    }

    /// An actor passed or returned as a reference: `{"id": …}`. `@Discoverable`
    /// actors use it as their schema; give it to other distributed actors used in
    /// signatures with a `Describable` conformance.
    ///
    /// `"x-actor-reference": true` tells callers the object refers to an actor, so they
    /// can tell it apart from data that happens to have an `id` field.
    public static var actorReferenceSchema: JSONValue {
        ["type": "object", "properties": ["id": [:]], "required": ["id"], "x-actor-reference": true]
    }

    /// A W3C-style read-only property affordance with its schema fields at the top level.
    static func propertySchema(for type: Any.Type, description: String?) -> JSONValue {
        guard case .object(var property) = schema(for: type) else { return schema(for: type) }
        if let description { property["description"] = .string(description) }
        property["readOnly"] = .bool(true)
        return .object(property)
    }

    static func json<Value: Encodable>(_ value: Value) throws -> JSONValue {
        try JSONValue(encoding: value)
    }

    /// Adds a description to a schema, alongside a `$ref` if there is one.
    public static func describing(_ schema: JSONValue, _ summary: String?) -> JSONValue {
        guard let summary, case .object(var object) = schema else { return schema }
        object["description"] = .string(summary)
        return .object(object)
    }

    /// The JSON Schema for a Swift type, as far as it's known at runtime.
    ///
    /// Types without a schema of their own are described as `{}`, which accepts any value.
    public static func schema(for type: Any.Type) -> JSONValue {
        if let schema = leafSchema(for: type) { return schema }
        // Actor arguments are passed as the same reference an actor result is returned as.
        if type is any DistributedActor.Type { return actorReferenceSchema }
        if let type = type as? any _DiscoveryOptional.Type {
            return ["anyOf": [schema(for: type.wrappedType), ["type": "null"]]]
        }
        if let type = type as? any _DiscoveryArray.Type {
            return ["type": "array", "items": schema(for: type.elementType)]
        }
        if let type = type as? any _DiscoveryStringDictionary.Type {
            return ["type": "object", "additionalProperties": schema(for: type.valueType)]
        }
        // Other types are described only by their own schema, from `@Describable` or a
        // hand-written conformance. Nothing is inferred by running their decoders.
        return [:]
    }

    /// Schemas known without looking inside the type.
    static func leafSchema(for type: Any.Type) -> JSONValue? {
        (type as? any Describable.Type)?.jsonSchema
    }
}

// Runtime access to generic arguments of standard containers.

public protocol _DiscoveryOptional { static var wrappedType: Any.Type { get } }
extension Optional: _DiscoveryOptional { public static var wrappedType: Any.Type { Wrapped.self } }

public protocol _DiscoveryArray { static var elementType: Any.Type { get } }
extension Array: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }
extension Set: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }

public protocol _DiscoveryStringDictionary { static var valueType: Any.Type { get } }
extension Dictionary: _DiscoveryStringDictionary where Key == String {
    public static var valueType: Any.Type { Value.self }
}

/// Support for code generated by ``Discoverable()`` and ``Describable()``.
///
/// Generated code runs in your module, so these are public, but they aren't meant to be
/// called directly and may change without notice.
public enum _DiscoverySupport {
    public static func schema(description: String?, parameters: [Discovery.Parameter]) -> JSONValue? {
        Discovery.schema(description: description, parameters: parameters)
    }

    public static func objectSchema(description: String?, fields: [Discovery.Parameter]) -> JSONValue {
        Discovery.objectSchema(description: description, fields: fields)
    }

    public static func enumSchema(
        description: String?,
        cases: [(value: JSONValue, description: String?)]
    ) -> JSONValue {
        Discovery.enumSchema(description: description, cases: cases)
    }

    public static func taggedSchema(
        description: String?,
        cases: [(name: String, description: String?, fields: [Discovery.Parameter])]
    ) -> JSONValue {
        Discovery.taggedSchema(description: description, cases: cases)
    }

    public static func propertySchema(for type: Any.Type, description: String?) -> JSONValue {
        Discovery.propertySchema(for: type, description: description)
    }

    /// Compiles only for a type with a schema, so a signature using a type without
    /// one fails to build instead of describing it as `{}`.
    public static func described<Value: Describable>(_ type: Value.Type) -> Value.Type {
        type
    }

    /// The schema of a discoverable actor used in a signature: a reference, `{"id": …}`.
    public static var actorReferenceSchema: JSONValue {
        Discovery.actorReferenceSchema
    }

    public static func validate(_ arguments: JSONValue, allowedKeys: [String]) throws {
        try Discovery.validate(arguments, allowedKeys: allowedKeys)
    }

    public static func argument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value {
        try Discovery.argument(type, name, in: arguments, actorSystem: actorSystem)
    }

    public static func optionalArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value? {
        try Discovery.optionalArgument(type, name, in: arguments, actorSystem: actorSystem)
    }

    public static func defaultedArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil,
        default defaultValue: @autoclosure () -> Value
    ) throws -> Value {
        try Discovery.defaultedArgument(
            type, name, in: arguments, actorSystem: actorSystem, default: defaultValue())
    }

    public static func json<Value: Encodable>(_ value: Value) throws -> JSONValue {
        try Discovery.json(value)
    }
}
