public import Distributed

/// A type that supplies its own JSON Schema to discovery, instead of the one
/// inferred from its `Codable` conformance. Use it for descriptions, formats,
/// or constraints that `Codable` can't express, or for types that can't be
/// inferred, such as `RawRepresentable` enums that aren't `CaseIterable`.
public protocol JSONSchemaRepresentable {
    static var jsonSchema: JSONValue { get }
}

/// Support for code generated by ``Discoverable()``.
///
/// Other modules can add more constrained overloads of ``parameter(_:description:type:)``
/// in an extension; code generated in those modules picks them up.
public enum Discovery {
    /// One argument of an action.
    public struct Parameter: Sendable {
        public var name: String
        public var schema: JSONValue
        public var isOptional: Bool

        public init(name: String, schema: JSONValue, isOptional: Bool) {
            self.name = name
            self.schema = schema
            self.isOptional = isOptional
        }
    }

    public static func schema(description: String?, parameters: [Parameter]) -> JSONValue? {
        guard !parameters.isEmpty else { return nil }
        var properties: [String: JSONValue] = [:]
        for parameter in parameters {
            properties[parameter.name] = parameter.schema
        }
        var object: [String: JSONValue] = [
            "type": "object",
            "properties": .object(properties),
            "required": .array(parameters.filter { !$0.isOptional }.map { .string($0.name) }),
            "additionalProperties": false,
        ]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of a structure's fields, for code generated by ``JSONSchema()``.
    public static func objectSchema(description: String?, fields: [Parameter]) -> JSONValue {
        var properties: [String: JSONValue] = [:]
        for field in fields {
            properties[field.name] = field.schema
        }
        var object: [String: JSONValue] = [
            "type": "object",
            "properties": .object(properties),
            "required": .array(fields.filter { !$0.isOptional }.map { .string($0.name) }),
        ]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of an enumeration's raw values, for code generated by ``JSONSchema()``.
    ///
    /// Values with descriptions are listed as `oneOf` constants, so each keeps its description.
    public static func enumSchema(description: String?, cases: [(value: JSONValue, description: String?)]) -> JSONValue
    {
        var object: [String: JSONValue] = [:]
        if let first = cases.first?.value {
            object["type"] =
                if case .string = first { "string" } else if case .number = first { "number" } else { "integer" }
        }
        if cases.contains(where: { $0.description != nil }) {
            object["oneOf"] = .array(cases.map { describing(["const": $0.value], $0.description) })
        } else {
            object["enum"] = .array(cases.map(\.value))
        }
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    /// The schema of an enumeration with associated values, in the shape synthesized `Codable`
    /// produces: an object with one key, the case name, holding the associated values.
    public static func taggedSchema(
        description: String?,
        cases: [(name: String, description: String?, fields: [Parameter])]
    ) -> JSONValue {
        let options: [JSONValue] = cases.map { tagged in
            [
                "type": "object",
                "properties": [tagged.name: objectSchema(description: tagged.description, fields: tagged.fields)],
                "required": [.string(tagged.name)],
                "additionalProperties": false,
            ]
        }
        var object: [String: JSONValue] = ["oneOf": .array(options)]
        if let description { object["description"] = .string(description) }
        return .object(object)
    }

    public static func validate(_ arguments: JSONValue, allowedKeys: [String]) throws {
        guard case .object(let values) = arguments else {
            if arguments == .null { return }
            throw DiscoveryError.invalidArgument(
                name: "arguments", reason: "expected object, got \(kind(of: arguments))")
        }
        if let extra = values.keys.sorted().first(where: { !allowedKeys.contains($0) }) {
            throw DiscoveryError.unexpectedArgument(extra)
        }
    }

    public static func parameter<Value: Decodable>(
        _ name: String,
        description: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), description), isOptional: false)
    }

    public static func optionalParameter<Value: Decodable>(
        _ name: String,
        description: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), description), isOptional: true)
    }

    public static func argument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value {
        guard let value = try optionalArgument(type, name, in: arguments, actorSystem: actorSystem) else {
            throw DiscoveryError.missingArgument(name)
        }
        return value
    }

    public static func optionalArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil
    ) throws -> Value? {
        guard let value = arguments[name], value != .null else { return nil }
        return try decodeArgument(type, name, from: value, actorSystem: actorSystem)
    }

    public static func defaultedArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue,
        actorSystem: (any DistributedActorSystem)? = nil,
        default defaultValue: @autoclosure () -> Value
    ) throws -> Value {
        guard let value = arguments[name] else { return defaultValue() }
        return try decodeArgument(type, name, from: value, actorSystem: actorSystem)
    }

    /// Decodes an argument, turning a `DecodingError`, which actor systems can't send back to a
    /// remote caller, into ``DiscoveryError/invalidArgument(name:reason:)``.
    ///
    /// A distributed actor argument is passed as the reference `invoke` returns for it,
    /// `{"id": …}`, and resolved with the receiving actor's system.
    private static func decodeArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        from value: JSONValue,
        actorSystem: (any DistributedActorSystem)?
    ) throws -> Value {
        let value = try unwrappingReferences(value, as: type, argument: name)
        do {
            return try value.decode(type, actorSystem: actorSystem)
        } catch let error as DecodingError {
            throw DiscoveryError.invalidArgument(name: name, reason: reason(for: error, in: value))
        } catch {
            // A hand-written `init(from:)` may throw its own validation error.
            throw DiscoveryError.invalidArgument(name: name, reason: String(describing: error))
        }
    }

    /// Replaces each `{"id": …}` reference with the ID it holds, wherever `type` has a
    /// distributed actor: directly, as an optional, or inside arrays and string-keyed
    /// dictionaries, the same places ``schema(for:)`` describes references.
    private static func unwrappingReferences(
        _ value: JSONValue,
        as type: Any.Type,
        argument name: String,
        path: String = ""
    ) throws -> JSONValue {
        if value == .null { return value }
        if let optional = type as? any _DiscoveryOptional.Type {
            return try unwrappingReferences(value, as: optional.wrappedType, argument: name, path: path)
        }
        if type is any DistributedActor.Type {
            guard case .object(let fields) = value, let id = fields["id"] else {
                let location = path.isEmpty ? "" : " at \(path)"
                throw DiscoveryError.invalidArgument(
                    name: name, reason: #"expected object with "id", got \#(kind(of: value))\#(location)"#)
            }
            return id
        }
        if let array = type as? any _DiscoveryArray.Type, case .array(let elements) = value {
            return .array(
                try elements.enumerated().map { index, element in
                    try unwrappingReferences(element, as: array.elementType, argument: name, path: "\(path)[\(index)]")
                })
        }
        if let dictionary = type as? any _DiscoveryStringDictionary.Type, case .object(let fields) = value {
            var unwrapped: [String: JSONValue] = [:]
            for (key, field) in fields {
                let fieldPath = path.isEmpty ? key : "\(path).\(key)"
                unwrapped[key] = try unwrappingReferences(
                    field, as: dictionary.valueType, argument: name, path: fieldPath)
            }
            return .object(unwrapped)
        }
        return value
    }

    /// Wraps each distributed actor's encoded ID as a reference, `{"id": …}`, wherever
    /// `type` has one, so results match the schemas ``schema(for:)`` gives them.
    private static func wrappingReferences(_ value: JSONValue, as type: Any.Type) -> JSONValue {
        if value == .null { return value }
        if let optional = type as? any _DiscoveryOptional.Type {
            return wrappingReferences(value, as: optional.wrappedType)
        }
        if type is any DistributedActor.Type { return ["id": value] }
        if let array = type as? any _DiscoveryArray.Type, case .array(let elements) = value {
            return .array(elements.map { wrappingReferences($0, as: array.elementType) })
        }
        if let dictionary = type as? any _DiscoveryStringDictionary.Type, case .object(let fields) = value {
            return .object(fields.mapValues { wrappingReferences($0, as: dictionary.valueType) })
        }
        return value
    }

    /// A short explanation of a decoding failure in JSON terms, such as
    /// `expected integer, got string at authors[0].born`.
    static func reason(for error: DecodingError, in value: JSONValue) -> String {
        switch error {
        case .typeMismatch(let type, let context):
            let found = value.value(at: context.codingPath).map(kind(of:)) ?? "nothing"
            return "expected \(kind(of: type)), got \(found)\(location(context.codingPath))"
        case .valueNotFound(let type, let context):
            return "expected \(kind(of: type)), got null\(location(context.codingPath))"
        case .keyNotFound(let key, let context):
            return "missing \"\(key.stringValue)\"\(location(context.codingPath))"
        case .dataCorrupted(let context):
            return "\(context.debugDescription)\(location(context.codingPath))"
        @unknown default:
            return "\(error)"
        }
    }

    private static func location(_ path: [any CodingKey]) -> String {
        guard !path.isEmpty else { return "" }
        var text = ""
        for key in path {
            if let index = key.intValue {
                text += "[\(index)]"
            } else {
                text += text.isEmpty ? key.stringValue : ".\(key.stringValue)"
            }
        }
        return " at \(text)"
    }

    /// The JSON kind a type decodes from, taken from its schema, so that types such as
    /// `Decimal` or `UUID` are reported by their JSON form rather than their Swift name.
    private static func kind(of type: Any.Type) -> String {
        if case .string(let kind)? = schema(for: type)["type"] { return kind }
        return "\(type)"
    }

    private static func kind(of value: JSONValue) -> String {
        switch value {
        case .null: "null"
        case .bool: "boolean"
        case .integer, .unsignedInteger: "integer"
        case .number: "number"
        case .string: "string"
        case .array: "array"
        case .object: "object"
        }
    }

    public static var void: JSONValue { .null }

    /// The JSON Schema for the tagged result returned by `invoke`.
    ///
    public static func resultSchema(for type: Any.Type) -> JSONValue {
        if let reference = referenceSchema(for: type) {
            return taggedResult("actor", reference)
        }
        // `result(_:actorSystem:)` returns a present actor as a reference and `nil` as JSON null.
        if let optional = type as? any _DiscoveryOptional.Type,
            let reference = referenceSchema(for: optional.wrappedType)
        {
            return ["anyOf": [taggedResult("actor", reference), taggedResult("json", ["type": "null"])]]
        }
        return taggedResult("json", schema(for: type))
    }

    /// The schema of the ``ActorReference`` returned for an actor; `nil` for other types.
    private static func referenceSchema(for type: Any.Type) -> JSONValue? {
        guard type is any DiscoverableActor.Type else { return nil }
        return actorReferenceSchema
    }

    /// An actor passed or returned as a reference: `{"id": …}`.
    static var actorReferenceSchema: JSONValue {
        ["type": "object", "properties": ["id": [:]], "required": ["id"]]
    }

    private static func taggedResult(_ kind: String, _ valueSchema: JSONValue) -> JSONValue {
        [
            "type": "object",
            "properties": [kind: valueSchema],
            "required": .array([.string(kind)]),
            "additionalProperties": false,
        ]
    }

    /// A W3C-style read-only property affordance with its schema fields at the top level.
    public static func propertySchema(for type: Any.Type, description: String?) -> JSONValue {
        guard case .object(var property) = schema(for: type) else { return schema(for: type) }
        if let description { property["description"] = .string(description) }
        property["readOnly"] = .bool(true)
        return .object(property)
    }

    public static func result<System: DistributedActorSystem<any Codable>, Value: Encodable>(
        _ value: Value,
        actorSystem: System.Type
    ) throws -> ActionResult {
        if let actor = value as? any DiscoverableActor {
            guard actor.actorSystem is System,
                let identifier = actor.id as? any Encodable
            else {
                throw DiscoveryError.invalidActorReference
            }
            return .actor(ActorReference(identifier: try JSONValue(encoding: identifier)))
        }
        // Other actors, such as elements of `[Loan]` or actors that aren't discoverable,
        // become references inside the JSON, as their schema says.
        return .json(wrappingReferences(try json(value), as: Value.self))
    }

    /// A property's value, with actors in it as references, `{"id": …}`, as its schema says.
    public static func propertyValue<Value: Encodable>(_ value: Value) throws -> JSONValue {
        wrappingReferences(try json(value), as: Value.self)
    }

    public static func json<Value: Encodable>(_ value: Value) throws -> JSONValue {
        try JSONValue(encoding: value)
    }

    /// Adds a description to a schema, alongside a `$ref` if there is one.
    public static func describing(_ schema: JSONValue, _ summary: String?) -> JSONValue {
        guard let summary, case .object(var object) = schema else { return schema }
        object["description"] = .string(summary)
        return .object(object)
    }

    /// The JSON Schema for a Swift type, as far as it's known at runtime.
    ///
    /// Other `Decodable` types, such as structures with synthesized `Codable`
    /// conformances, are described by probing their `init(from:)`. Types that
    /// can't be probed accept any value.
    public static func schema(for type: Any.Type) -> JSONValue {
        if let schema = leafSchema(for: type) { return schema }
        // Actor arguments are passed as the same reference an actor result is returned as.
        if type is any DistributedActor.Type { return actorReferenceSchema }
        if let type = type as? any _DiscoveryOptional.Type {
            return ["anyOf": [schema(for: type.wrappedType), ["type": "null"]]]
        }
        if let type = type as? any _DiscoveryArray.Type {
            return ["type": "array", "items": schema(for: type.elementType)]
        }
        if let type = type as? any _DiscoveryStringDictionary.Type {
            return ["type": "object", "additionalProperties": schema(for: type.valueType)]
        }
        if let type = type as? any Decodable.Type, let schema = SchemaProbe.schema(for: type) {
            return schema
        }
        return [:]
    }

    /// Schemas known without looking inside the type.
    static func leafSchema(for type: Any.Type) -> JSONValue? {
        if let type = type as? any JSONSchemaRepresentable.Type { return type.jsonSchema }
        if type == String.self { return ["type": "string"] }
        if type == Bool.self { return ["type": "boolean"] }
        if type is any BinaryInteger.Type { return ["type": "integer"] }
        if type is any BinaryFloatingPoint.Type { return ["type": "number"] }
        return nil
    }
}

// Runtime access to generic arguments of standard containers.

public protocol _DiscoveryOptional { static var wrappedType: Any.Type { get } }
extension Optional: _DiscoveryOptional { public static var wrappedType: Any.Type { Wrapped.self } }

public protocol _DiscoveryArray { static var elementType: Any.Type { get } }
extension Array: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }
extension Set: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }

public protocol _DiscoveryStringDictionary { static var valueType: Any.Type { get } }
extension Dictionary: _DiscoveryStringDictionary where Key == String {
    public static var valueType: Any.Type { Value.self }
}
