/// A type that supplies its own JSON Schema to discovery. Types without one
/// are described by their structure where it's known (strings, numbers,
/// arrays, optionals) and otherwise accept any value.
public protocol JSONSchemaRepresentable {
    static var jsonSchema: JSONValue { get }
}

/// Support for code generated by ``Discoverable()``.
///
/// Other modules can add more constrained overloads of ``parameter(_:summary:type:)``
/// in an extension; code generated in those modules picks them up.
public enum Discovery {
    /// One argument of an action.
    public struct Parameter: Sendable {
        public var name: String
        public var schema: JSONValue
        public var isOptional: Bool

        public init(name: String, schema: JSONValue, isOptional: Bool) {
            self.name = name
            self.schema = schema
            self.isOptional = isOptional
        }
    }

    public static func schema(summary: String?, parameters: [Parameter]) -> JSONValue? {
        guard !parameters.isEmpty else { return nil }
        var properties: [String: JSONValue] = [:]
        for parameter in parameters {
            properties[parameter.name] = parameter.schema
        }
        var object: [String: JSONValue] = [
            "type": "object",
            "properties": .object(properties),
            "required": .array(parameters.filter { !$0.isOptional }.map { .string($0.name) }),
            "additionalProperties": false,
        ]
        if let summary { object["description"] = .string(summary) }
        return .object(object)
    }

    public static func validate(_ arguments: JSONValue, allowedKeys: [String]) throws {
        guard case .object(let values) = arguments else {
            if arguments == .null { return }
            throw DiscoveryError.invalidArguments
        }
        if let extra = values.keys.sorted().first(where: { !allowedKeys.contains($0) }) {
            throw DiscoveryError.unexpectedArgument(extra)
        }
    }

    public static func parameter<Value: Decodable>(
        _ name: String,
        summary: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), summary), isOptional: false)
    }

    public static func optionalParameter<Value: Decodable>(
        _ name: String,
        summary: String?,
        type: Value.Type
    ) -> Parameter {
        Parameter(name: name, schema: describing(schema(for: type), summary), isOptional: true)
    }

    public static func argument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue
    ) throws -> Value {
        guard let value = try optionalArgument(type, name, in: arguments) else {
            throw DiscoveryError.missingArgument(name)
        }
        return value
    }

    public static func optionalArgument<Value: Decodable>(
        _ type: Value.Type,
        _ name: String,
        in arguments: JSONValue
    ) throws -> Value? {
        guard let value = arguments[name], value != .null else { return nil }
        return try value.decode(type)
    }

    public static var void: JSONValue { .null }

    public static func result<Value: Encodable>(_ value: Value) throws -> JSONValue {
        try JSONValue(encoding: value)
    }

    /// Adds a description to a schema, alongside a `$ref` if there is one.
    public static func describing(_ schema: JSONValue, _ summary: String?) -> JSONValue {
        guard let summary, case .object(var object) = schema else { return schema }
        object["description"] = .string(summary)
        return .object(object)
    }

    /// The JSON Schema for a Swift type, as far as it's known at runtime.
    public static func schema(for type: Any.Type) -> JSONValue {
        if let type = type as? any JSONSchemaRepresentable.Type { return type.jsonSchema }
        if type == String.self || type == Character.self { return ["type": "string"] }
        if type == Bool.self { return ["type": "boolean"] }
        if type is any BinaryInteger.Type { return ["type": "integer"] }
        if type is any BinaryFloatingPoint.Type { return ["type": "number"] }
        if let type = type as? any _DiscoveryOptional.Type { return schema(for: type.wrappedType) }
        if let type = type as? any _DiscoveryArray.Type {
            return ["type": "array", "items": schema(for: type.elementType)]
        }
        if let type = type as? any _DiscoveryStringDictionary.Type {
            return ["type": "object", "additionalProperties": schema(for: type.valueType)]
        }
        return [:]
    }
}

// Runtime access to generic arguments of standard containers.

public protocol _DiscoveryOptional { static var wrappedType: Any.Type { get } }
extension Optional: _DiscoveryOptional { public static var wrappedType: Any.Type { Wrapped.self } }

public protocol _DiscoveryArray { static var elementType: Any.Type { get } }
extension Array: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }
extension Set: _DiscoveryArray { public static var elementType: Any.Type { Element.self } }

public protocol _DiscoveryStringDictionary { static var valueType: Any.Type { get } }
extension Dictionary: _DiscoveryStringDictionary where Key == String {
    public static var valueType: Any.Type { Value.self }
}
